name: Terraform - PR Review

on:
  pull_request:

jobs:
  list-modules:
    name: Terraform - List Terraform modules
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@master
      - run: sudo apt-get install jq
      - id: set-matrix
        run: |
          git fetch --all
          echo "::set-output name=matrix::$(git diff --name-status origin/${{ github.base_ref }} | cut -f2 | grep '.tf' | sed -r 's|/[^/]+$||' | sed -r 's|(.+)|"\1"|g' | sort | uniq | jq -sc '{include: [(.[] | {module: .})]}')"

  terraform-modules:
    name: Terraform - Check modules
    runs-on: ubuntu-latest
    needs: list-modules
    strategy:
      matrix: ${{fromJson(needs.list-modules.outputs.matrix)}}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Setup Node
        uses: actions/setup-node@master

      - name: Terraform - recommended Standard Module Struture
        id: tf_struct
        run: |
          test -f main.tf
          test -f outputs.tf
          test -f variables.tf
          test -f version.tf
          test -f README.md
        working-directory: ${{ matrix.module }}
      - name: Terraform - syntax
        id: tf_lint
        run: terraform fmt -check -recursive
        working-directory: ${{ matrix.module }}
      - name: Docs - text lint
        id: doc_lint
        uses: tsuyoshicho/action-textlint@v3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          textlint_flags: "${{ matrix.module }}/README.md"
